### PR TITLE
Starter kits

### PR DESCRIPTION
**Pull request by rofrol**

### CODE REVIEW

**Comment by milankinen** [comment]
I don't understand how `react-hot-boilerplate` relates to livereactload. In addition, pull requests must be merged into `development`.

Closing this one

**Comment by rofrol** [comment]
Look at this site https://github.com/gaearon/react-hot-loader/tree/master/docs#starter-kits

They list starter kits

**Comment by gaearon** [comment]
@rofrol 

React Hot Boilerplate uses React Hot Loader.
LiveReactload does not.

These are unrelated projects.

**Comment by rofrol** [comment]
Right, my mistake. I wanted to add my project https://github.com/rofrol/react-starter-kit

**Pull request closed without merging**
