### PR TITLE
Feature/bump ws version

### PR DESCRIPTION
**Pull request by subshad**
On Node@v4.1.0 and Npm@v3.3.0 this package currently fails to install, due to a dependency on socket.io@v0.7.2 which depends on buffer-util@1.1.0. There is a fix in buffer-util@1.2.0 which is used by socket.io@v0.8.0.

I was unable to get your test suite to run, but if you can show me how to I can run the tests and check if there are any regressions.

Thank you :)

### CODE REVIEW

**Comment by subshad** [comment]
Sorry, I didn't see the 2.0.0 alpha. I'll close this and try that in my project.

**Comment by milankinen** [comment]
@subshad of course we can update package version also in legacy branch! I'll re-open and merge this to the legacy branch so that we can get this working with node v4.

**Comment by milankinen** [comment]
Could you please let `livereactload` package version unchanged? I have some other changes to commit so I'll increment the package version and write release notes after all stuff is added.

**Comment by subshad** [comment]
Of course :) I've undone that version change and just left the socket.io bump.

**Comment by milankinen** [comment]
Thanks!

**Pull request merged**
