### PR TITLE
Re-write module (re)loading logic

### LINKED ISSUE #117: aborts with external dependencies
with the following grunt browserify config:
```js
browserify: {
  options: {
    transform: [
        ['babelify', { presets: [ 'es2015', 'react' ]}],
    ],
    plugin: [ 'livereactload', ],
    extensions: ['.jsx'],
   },
  app: {
    src:  jsDir + '/App/Routes.js',
    dest: publicDir + 'js/app.js',  
    options: {
        external: reactVendor, // ['react', 'react-dom'] // etc
    }
  },
  vendor: {
    src: ['.'],
    dest: publicDir + 'js/vendor.js',
    options: {
        alias: reactVendor.map(function(module) {
            return module + ':';
        }),
    },
  },
}
```
I get the following error:
```js
LiveReactload :: Apply patch
> Patch module    :: /www/app/resources/assets/js/App/ReactComponents/Member.jsx
Error: No react(…)(anonymous function) @ VM17437:78handleChanges @ VM17437:53change @ ws.onmessage 
LiveReactload :: Abort patching
```
Members.jsx requires 'react' which is present in `vendor.js`
Could be external parameter be ignored ?

### PR DESCRIPTION
**Pull request by milankinen**
Sorry for late responses and thanks for the patience. My master's thesis has taken my whole attention during the last month so responses to this project (and my other OS stuff as well..) have been awfully slow.

However, this PR tries to fix the existing problems regarding to reloading bugs. I'll try to release a beta version with new reloading logic ASAP so that you can test whether the new reloading logic solves the existing problems or not.

This (hopefully) fixes #117 #114 #113 #112 #111 and #104.

### CODE REVIEW

**Comment by milankinen** [comment]
Okay, I just published new version as a beta tag so you can install it by giving version number explicitly:
```
npm i livereactload@2.3.0-rc1
```

If you still have the issues / your issues are solved, please report them to this PR. I'll keep this version as a beta until they (or at least most of them) are fixed.

Ping @luckyraul @mlarcher @mikeebee @ilovepumpkin @nvartolomei @callumacrae @dolfelt @ganemone @younes0 (sorry spam)

**Comment by ilovepumpkin** [comment]
Hi @milankinen, thanks for working on this issue first. 

I saw the following errors in console. I tried to add a breakpoint at the line 15 in VM103, what I saw is the keys function was invoked twice. At the first time, the obj looks normal, which contains files with their path as keys, but the second time it is undefined, which is why the error is shown the console. 

image

image

**Comment by milankinen** [comment]
@ilovepumpkin It seems that you still have the old version. Did you install the new version with command `npm install --save-dev livereactload@2.3.0-rc1`?

**Comment by luckyraul** [comment]
In my case it's working good

**Comment by younes0** [comment]
according to this
image

entryId is invalid
```js
  function reload(changes) {
  //... 

    try {
      info("Applying changes...");
      evaluate(entryId);
      info("Reload complete!");
    } catch (e) {
      console.error(e);
      error("Error occurred while reloading changes. Restoring old implementation...");
      try {
        restore();
        evaluate(entryId);
      } catch (re) {
        console.error(re);
        error("Restore failed. You may need to refresh your browser... :-/");
      }
    }
  //... 
```

**Comment by milankinen** [comment]
@luckyraul nice 👍 

@younes0 I made another release `2.3.0-rc2` with improved logging. Can you install it, turn the new debug logging on (`-p [ livereactload --debug ]` if using CLI, `{debug: true}` if using JS API) and send the error log (or at least relevant parts: "entries" and "Module causing the error") here?

**Comment by younes0** [comment]
image

```js
LiveReactload [DEBUG] :: Compiling module Object {id: "/www/icra/icram/resources/assets/js/Icram/Base.js", hash: "267d3ab1aa2368cc6f5f26cb8497e137", browserifyId: 1}
LiveReactload [DEBUG] :: Compiling module Object {id: "/www/icra/icram/resources/assets/js/Icram/Components/Member.jsx", hash: "3c6cc3a7388bb38e6521468109127fa7", browserifyId: 2}
LiveReactload [DEBUG] :: Compiling module Object {id: "/www/icra/icram/resources/assets/js/Icram/Components/MembersList.jsx", hash: "d3565c027eb24926616f0fc994b9700d", browserifyId: 3}
LiveReactload [DEBUG] :: Compiling module Object {id: "/www/icra/icram/resources/assets/js/Icram/Donate.js", hash: "8d466512d53a1c54ad5d19308037d843", browserifyId: 4}
LiveReactload [DEBUG] :: Compiling module Object {id: "/www/icra/icram/resources/assets/js/Icram/Members.jsx", hash: "5841a31304f1c07918804bc6860bf778", browserifyId: 5}
LiveReactload [DEBUG] :: Compiling module Object {id: "/www/icra/icram/resources/assets/js/Icram/Routes.js", hash: "e28c8170e26bfa2b3d92862958bf1fc3", browserifyId: 6}
LiveReactload [DEBUG] :: Compiling module Object {id: "/www/icra/icram/resources/assets/js/Icram/Users.js", hash: "5813c7bc57dff1bf4ef99ad89f9a96af", browserifyId: 7}
LiveReactload [DEBUG] :: Compiling module Object {id: "/www/icra/icram/resources/assets/js/Yeb/Admin/Datatable.js", hash: "592be985c141ccc0dafebf59d09436b3", browserifyId: 8}
LiveReactload [DEBUG] :: Compiling module Object {id: "/www/icra/icram/resources/assets/js/Yeb/Admin/Layout.js", hash: "0853b44812b2cea845e1ccc940d73111", browserifyId: 9}
LiveReactload [DEBUG] :: Compiling module Object {id: "/www/icra/icram/resources/assets/js/Yeb/Helpers/Modal.js", hash: "060a061ef9f3f748b0c3e03797c990ca", browserifyId: 10}
LiveReactload [DEBUG] :: Compiling module Object {id: "/www/icra/icram/resources/assets/js/Yeb/Helpers/Other.js", hash: "defc80667b1da6ffcf7d4fc8be9d2338", browserifyId: 11}
LiveReactload [DEBUG] :: Options: Object {nodeModulesRoot: "/www/icra/icram/node_modules", port: 4474, host: null, clientEnabled: true, debug: true}
LiveReactload [DEBUG] :: Entries: ["/www/icra/icram/resources/assets/js/Icram/Routes.js"] /www/icra/icram/resources/assets/js/Icram/Routes.js
LiveReactload [DEBUG] :: Mappings
LiveReactload :: WebSocket client listening for changes...
LiveReactload :: Bundle changed
LiveReactload [DEBUG] :: Compiling module Object {id: "/www/icra/icram/resources/assets/js/Icram/Components/MembersList.jsx", hash: "77c8b4ce35041512b1f83810ac79a6d5", browserifyId: 3}
LiveReactload :: Applying changes...
LiveReactload [DEBUG] :: Changed modules ["/www/icra/icram/resources/assets/js/Icram/Components/MembersList.jsx"]
LiveReactload [DEBUG] :: New modules []
LiveReactload [DEBUG] :: Evaluate module /www/icra/icram/resources/assets/js/Icram/Routes.js
LiveReactload [DEBUG] :: Dependencies for /www/icra/icram/resources/assets/js/Icram/Routes.js - ["/www/icra/icram/resources/assets/js/Icram/Donate.js", "/www/icra/icram/resources/assets/js/Icram/Base.js", "/www/icra/icram/resources/assets/js/Icram/Users.js", "/www/icra/icram/resources/assets/js/Icram/Members.jsx"]
LiveReactload [DEBUG] :: Evaluate module /www/icra/icram/resources/assets/js/Icram/Donate.js
LiveReactload [DEBUG] :: Dependencies for /www/icra/icram/resources/assets/js/Icram/Donate.js - ["/www/icra/icram/resources/assets/js/Icram/Base.js"]
LiveReactload [DEBUG] :: Evaluate module /www/icra/icram/resources/assets/js/Icram/Base.js
LiveReactload [DEBUG] :: Dependencies for /www/icra/icram/resources/assets/js/Icram/Base.js - ["/www/icra/icram/resources/assets/js/Yeb/Admin/Layout.js"]
LiveReactload [DEBUG] :: Evaluate module /www/icra/icram/resources/assets/js/Yeb/Admin/Layout.js
LiveReactload [DEBUG] :: Dependencies for /www/icra/icram/resources/assets/js/Yeb/Admin/Layout.js - ["/www/icra/icram/resources/assets/js/Yeb/Helpers/Modal.js"]
LiveReactload [DEBUG] :: Evaluate module /www/icra/icram/resources/assets/js/Yeb/Helpers/Modal.js
LiveReactload [DEBUG] :: Dependencies for /www/icra/icram/resources/assets/js/Yeb/Helpers/Modal.js - []
LiveReactload [DEBUG] :: Evaluate module /www/icra/icram/resources/assets/js/Icram/Base.js
LiveReactload [DEBUG] :: Dependencies for /www/icra/icram/resources/assets/js/Icram/Base.js - ["/www/icra/icram/resources/assets/js/Yeb/Admin/Layout.js"]
LiveReactload [DEBUG] :: Evaluate module /www/icra/icram/resources/assets/js/Yeb/Admin/Layout.js
LiveReactload [DEBUG] :: Dependencies for /www/icra/icram/resources/assets/js/Yeb/Admin/Layout.js - ["/www/icra/icram/resources/assets/js/Yeb/Helpers/Modal.js"]
LiveReactload [DEBUG] :: Evaluate module /www/icra/icram/resources/assets/js/Yeb/Helpers/Modal.js
LiveReactload [DEBUG] :: Dependencies for /www/icra/icram/resources/assets/js/Yeb/Helpers/Modal.js - []
LiveReactload [DEBUG] :: Evaluate module /www/icra/icram/resources/assets/js/Icram/Users.js
LiveReactload [DEBUG] :: Dependencies for /www/icra/icram/resources/assets/js/Icram/Users.js - ["/www/icra/icram/resources/assets/js/Icram/Base.js", "/www/icra/icram/resources/assets/js/Yeb/Admin/Datatable.js"]
LiveReactload [DEBUG] :: Evaluate module /www/icra/icram/resources/assets/js/Icram/Base.js
LiveReactload [DEBUG] :: Dependencies for /www/icra/icram/resources/assets/js/Icram/Base.js - ["/www/icra/icram/resources/assets/js/Yeb/Admin/Layout.js"]
LiveReactload [DEBUG] :: Evaluate module /www/icra/icram/resources/assets/js/Yeb/Admin/Layout.js
LiveReactload [DEBUG] :: Dependencies for /www/icra/icram/resources/assets/js/Yeb/Admin/Layout.js - ["/www/icra/icram/resources/assets/js/Yeb/Helpers/Modal.js"]
LiveReactload [DEBUG] :: Evaluate module /www/icra/icram/resources/assets/js/Yeb/Helpers/Modal.js
LiveReactload [DEBUG] :: Dependencies for /www/icra/icram/resources/assets/js/Yeb/Helpers/Modal.js - []
LiveReactload [DEBUG] :: Evaluate module /www/icra/icram/resources/assets/js/Yeb/Admin/Datatable.js
LiveReactload [DEBUG] :: Dependencies for /www/icra/icram/resources/assets/js/Yeb/Admin/Datatable.js - ["/www/icra/icram/resources/assets/js/Yeb/Helpers/Other.js"]
LiveReactload [DEBUG] :: Evaluate module /www/icra/icram/resources/assets/js/Yeb/Helpers/Other.js
LiveReactload [DEBUG] :: Dependencies for /www/icra/icram/resources/assets/js/Yeb/Helpers/Other.js - ["/www/icra/icram/resources/assets/js/Yeb/Helpers/Modal.js"]
LiveReactload [DEBUG] :: Evaluate module /www/icra/icram/resources/assets/js/Yeb/Helpers/Modal.js
LiveReactload [DEBUG] :: Dependencies for /www/icra/icram/resources/assets/js/Yeb/Helpers/Modal.js - []
LiveReactload [DEBUG] :: Evaluate module /www/icra/icram/resources/assets/js/Icram/Members.jsx
LiveReactload [DEBUG] :: Dependencies for /www/icra/icram/resources/assets/js/Icram/Members.jsx - ["react", "react-dom", "/www/icra/icram/resources/assets/js/Icram/Base.js", "/www/icra/icram/resources/assets/js/Icram/Components/MembersList.jsx"]
LiveReactload [DEBUG] :: Evaluate module react
TypeError: Cannot read property '1' of undefined(…)
LiveReactload :: Error occurred while reloading changes. Restoring old implementation...
LiveReactload [DEBUG] :: Module causing the error Object {id: "/www/icra/icram/resources/assets/js/Icram/Members.jsx", deps: Object, meta: Object}deps: Objectid: "/www/icra/icram/resources/assets/js/Icram/Members.jsx"meta: Object__proto__: Object
TypeError: Cannot read property '1' of undefined(…)
LiveReactload :: Restore failed. You may need to refresh your browser... :-/
LiveReactload [DEBUG] :: Module causing the error Object {id: "/www/icra/icram/resources/assets/js/Icram/Members.jsx", deps: Object, meta: Object}
```

**Comment by milankinen** [comment]
Thanks @younes0 that was very helpful.

Should be (hopefully) fixed now: `2.3.0-rc3`

**Comment by younes0** [comment]
image

I'm trying to debug with this

**Comment by milankinen** [comment]
Thanks! According to the log, I'd say that at least external dependencies should be reloading correctly now. I think there might be something inside your `MemberList.jsx` module -- how is that `baseName` calculated?

It would help if you could reveal at least some parts (imports and how to derive `baseName`) from `MemberList.jsx`

**Comment by ilovepumpkin** [comment]
@milankinen , you are right - really sorry, I forgot to restart my app. However, after I restarting my app, I found it is broken. My app is in the middle of migrating from angular.js to react/redux, so it actually to launch a react component from an angular.js application. I tried to switch back to 2.2.4, my app works but livereactload stop working, :(. Any ideas ?

**Comment by younes0** [comment]
It seems that baseName.split is caused by almond https://github.com/requirejs/almond/issues/104

Please tell me if this can help you
image

**Comment by milankinen** [comment]
@ilovepumpkin Can you turn debug logging on (see above for instructions) and paste the log here? Or if your project is OS, link to repo could help as well.

@younes0 Okay this might make some sense. Could you enable (in Chrome) "Pause on exceptions" and "Pause on caught exceptions" and tell me what value `baseName` gets before crash? Or even better, if you `vendors.js` bundle doesn't contain anything secret, pasting its content here would enable me to do some debugging on my own.

**Comment by ilovepumpkin** [comment]
@milankinen , I have attached the screenshot with the debug info - I have to cover some information on it because this is a company project. So as you can see, we are using ngReact to use React components in Angular app. The error shows that the React component can not be found. Not sure if you have ever used ngReact, as an example below, the React component "HelloComponent" is not found now. I am not sure if you know anyone who is using livereactload with ngReact - maybe they can help confirm if livereactload could break ngReact usage. If not, I could write an ngReact example to see if I could reproduce the similar error. Certainly in case after seeing this information, you already know what's wrong with it, that would be fantastic, :). 

```
<body ng-app="app">
  <div ng-controller="helloController">
    <react-component name="HelloComponent" props="person" watch-depth="reference"/>
  </div>
</body>
```

image

**Comment by younes0** [comment]
@milankinen baseName is `true` before the crash.

The vendor file is located at: https://dl.dropboxusercontent.com/u/28560717/vendor-3a507edd.js

**Comment by milankinen** [comment]
@ilovepumpkin I have never used Angular so this is just shooting in the dark. However, according to docs I don't see any reason why LiveReactLoad wouldn't work with ngReact. How are you doing the component registration (https://github.com/ngReact/ngReact#the-react-component-directive `app.value('HelloComponent', HelloComponent);`)?

@younes0 Okay that was exactly I was guessing too. Sorry to keep busy but would you mind to test yet another time whether the new `2.3.0-rc4` version works or not?

**Comment by younes0** [comment]
@milankinen thank you for your time, and sorry that I can't debug but my node.js knowledge is very limited

With the latest update, I get this error:
image

Do you wish to get my source files and the grunt file ?

**Comment by milankinen** [comment]
Yeah if that's possible it'd be great. You can send private link e.g. to m.lankinen@iki.fi

**Comment by ilovepumpkin** [comment]
@milankinen - never mind. Actually I am quite new to Angular/React, and still trying to understand the framework my project is using, :). Anyway, you go ahead to deliver your fix if it works for others. And I will investigate my issue on my own - probably will need your help later. Can I contact you if I have questions about the code of livereactload?

**Comment by milankinen** [comment]
@younes0 I think I got your package working. I saw you used `livereactload` pluging in global grunt browserify config like:
```js
        browserify: {
            options: {
                ...
                plugin: [
                    ['livereactload', {
                        debug: true,
                    }],
                ]
            },
            app: {
                ...
            },
            vendorModules: {
                ...
            },
        }
```
This means that LiveReactLoad tries to inject it's loader to `vendorModules` as well, but the loader is not compatible with standalone bundles. Changing plugin to `app` config solved the issue in my computer. I also noted that you forgot to add `livereactload/babel-transform` which is needed for proper reload propagation control.

The changed Grunt browserify config looks like this:
```js
{
    options: {
        ... same as before ... except NO plugin
    },
    app: {
        ... same as before ...
        options: {
            // added:
            plugin: [
                ['livereactload', {
                    debug: true,
                }],
            ],
            transform: [
                ['babelify', {
                    presets: [ 'es2015', 'react' ],
                    "env": {
                        "development": {
                            "plugins": [
                                ["react-transform", {
                                    "transforms": [{
                                        "transform": "livereactload/babel-transform",
                                        "imports": ["react"]
                                    }]
                                }]
                            ]
                        }
                    }
                }]
            ]
        }
    },
    vendorModules: {
        ... same as before ...
    },
}
```

I hope this solves your issue. If it works with `2.3.0-rc4`, could you also test if it works with `2.3.0-rc3` as well?

**Comment by ilovepumpkin** [comment]
@milankinen , let me explain why the 2.3.0-rc2 breaks my app but 2.2.4 didn't. Hope this could give you some hints to help fix my problem, :). 

In my app, there is a .jsx file which is responsible as an entry to load other React component. Assume its name is All.jsx. Its code is something like below

```
var AllComponents={};
AllComponents.ComponentA=require('./ComponentA.jsx');
AllComponents.CompoentB=require('./ComponentB.jsx');
AllComponents.CompoentC=require('./ComponentC.jsx');
module.exports=AllComponents; 
```
And my angular app uses the React component likes below

`<react-component name="AllComponents.ComponentA" props="TableProps" watch-depth="value" />`

In 2.2.4, I see the following code in bundle.js. Actually the angular app is just to get the AllComponents from the window object. 

```
             (function() {
               require("livereactload/client", entryId$$).call(null,{"port":4474,"host":null});
window["AllComponents"] = 
require("./AllComponents.jsx", entryId$$);
             })();
```

but in 2.3.0-rc2, I see AllComponents.jsx just handled as other .jsx files so there is no "window["AllComponents"] ", which is why we see the error "Can not find the react component". 

Any clue about how to fix this? My guess is that if you see "module.exports=AllComponents; ", it should be added to the window object. Not sure if my understanding is correct or not.

**Comment by milankinen** [comment]
@ilovepumpkin Ahh now I see! So you're using `--standalone / -s` flag and making react components as their own bundle?

**Comment by ilovepumpkin** [comment]
@milankinen , I am not very sure. But in my gulpfile.js, I found the following code and the variable "moduleName" in the code is "AllComponents". So I guess the answer is "yes", :). 

```
var customOpts = {
  standalone: moduleName,
  cache: {}, // required for watchify
  packageCache: {}, // required for watchify
  fullPaths: true // required to be true only for watchify
};
```

**Comment by milankinen** [comment]
Yes. I'll make a new release tonight that supports UMD (standalone) and I'll ping you to test it. 😄

**Comment by ilovepumpkin** [comment]
@milankinen , no hurry, take your time, thanks in advance.

**Comment by milankinen** [comment]
@ilovepumpkin Should be working now in `2.3.0-rc5`

**Comment by ilovepumpkin** [comment]
@milankinen , a good news, a bad news and a very bad news, :).

The good news is that now my app could be loaded. 

The bad news is that when I tried to make a change, I saw the following error. After investigation,  I found this is caused by "cross references" (e.g. A requires B and B also requires A). And this will cause your evaluate function never end but back and force between A and B.  Fortunately for my case, I could break the "cross reference" because although the B is required by A but actually it is not really used so just delete the "require". However, you may need to think about how to handle this because others may have the real case of "cross reference".   

image

The very bad news is that even after resolving the "cross reference" the hot reloading is still not working. And sympton is very similar with the beginning - "Reload complete!" is reported but the page content is not loaded actually. 

image

I have checked the window object and found my component content held by window object is not changed - is this possible the reason why my page is not changed? But I do see the changed content in the scope.cache. Any more information you need, please let me know.

**Comment by milankinen** [comment]
@ilovepumpkin Thanks! Yeah, that circular dependency problem is already known (#121) and I have a fix but it's not released yet.

What concerns me more is that your changes don't get reloaded. The log clearly says that changes are detected and modules reloaded. However, there are no logs for patched components. That leaves at least these two possible options:

1. Are you using `react-transform` Babel plugin? That is required if you want to get your components reloaded
2. Are you using only pure components (function components)? Pure component's can't be detected 'cause they are just functions. In order to activate the reloading, the top-level component must be either ES6 class component or component created with `React.createComponent`.

**Comment by ilovepumpkin** [comment]
@milankinen , the option 2) should be no problem. The option 1) is very possible. I have tried to configure other react transforms but seems not working too, so I guess yours does not take effect. I am still investigating this.

**Comment by ilovepumpkin** [comment]
@milankinen , I am still not able to make any react transform plugins work, like react-transform-count-renders, react-transform-log-render, etc. So there must something wrong in my own project but I do need take more time to figure it out. You have helped me a lot - it does not make sense to hold you steps again due to my issue. Please go ahead to merge your code if you need. Thanks!

**Comment by mikeebee** [comment]
@milankinen, thanks for looking into this, much appreciated. I'm getting similar errors to @ilovepumpkin. So am I right in thinking that this is related to #121? 

live-reactload-error

**Comment by milankinen** [comment]
@ilovepumpkin Hmm, weird. They should work out of the box if you follow the README instructions. https://github.com/milankinen/livereactload/pull/118#issuecomment-231993656 contains also  instructions how to add `react-transform` to your gulp build.

@mikeebee Yes. Fix is on its way and probably tomorrow releasing new candidate with a fix to the recursion bug.

**Comment by milankinen** [comment]
@ilovepumpkin @mikeebee Just released `2.3.0-rc6` which hopefully fixes the infinite recursion bug.

**Comment by ilovepumpkin** [comment]
@mikeebee , here is my current result when make a change in .jsx file. The error is gone - I guess "Nothing to reload" should be my own issue. So I think  the circular dependency problem is fixed in rc6.

image

**Comment by milankinen** [comment]
@ilovepumpkin Are you sure that your changes are saved? Are the changes visible if you refresh your browser?

**Comment by ilovepumpkin** [comment]
@mikeebee , I tried again - now I see "Reload complete!" as before but no changes in UI . Yes, refreshing page manually can make my changes visible.

**Comment by milankinen** [comment]
So you see log lines something like this?
```
Applying changes...
> Reload module :: ....
> Reload module :: ....
Reload complete!
```

In that case, are you using any build systems? If yes (e.g. gulp), could I see your browserify setup and/or `.babelrc` (or other Babel configurations) contents?

**Comment by ilovepumpkin** [comment]
I am using gulp. 

The whole gulpfile.js is very long - I guess the following is related to browserify configuration.

```
var customOpts = {
  standalone: moduleName,
  cache: {}, // required for watchify
  packageCache: {}, // required for watchify
  fullPaths: true // required to be true only for watchify
};
var opts = assign({}, watchify.args, customOpts);
var b = watchify(browserify('./'+srcFile,opts));
b.plugin(require('css-modulesify'), {
  output: destCSSFolder + '/modules.css'
});
b.plugin(require('livereactload'), { });
b.on('update', bundle);
b.on('log', gutil.log);
gulp.task('rebundle-js', function() {
  bundle();
});

```

.babelrc 
```
{
  "presets": ["es2015", "react"],
  "env": {
    "development": {
      "plugins": [
        ["react-transform", {
          "transforms": [{
            "transform": "livereactload/babel-transform",
            "imports": ["react"]
          }]
        }]
      ]
    }
  }
}
```

**Comment by milankinen** [comment]
@ilovepumpkin Okay that looks correct. I assume those `watchify.args` contain the transforms, including `babelify`? Very odd indeed... 😕 

However, I released `2.3.0-rc7` which includes `react-transform` detection. Do you have any console warnings if you try to use this version?

**Comment by ilovepumpkin** [comment]
@milankinen , there is no any additional configurations in watchify.args. I added "b.transform(require('babelify'));" in gulefile.js. 

gulpfile.js
```
// normal JS
var customOpts = {
  standalone: moduleName,
  cache: {}, // required for watchify
  packageCache: {}, // required for watchify
  fullPaths: true // required to be true only for watchify
};
var opts = assign({}, watchify.args, customOpts);
var b = watchify(browserify('./'+srcFile,opts));
b.plugin(require('css-modulesify'), {
  output: destCSSFolder + '/modules.css'
});
b.plugin(require('livereactload'), { });
b.transform(require('babelify'));
b.on('update', bundle);
b.on('log', gutil.log);
gulp.task('rebundle-js', function() {
  bundle();
});
```

.babelrc
```
{
  "presets": ["es2015", "react", "stage-0"],
  "env": {
    "development": {
      "plugins": [
        ["react-transform", {
          "transforms": [{
            "transform": "livereactload/babel-transform",
            "imports": ["react"]
          }]
        }]
      ]
    }
  }
}
```

I did see your new message "LiveReactload :: LiveReactLoad transform detected. Ready to rock!", but my change is still not visible.

image

Any clue? Maybe this is really caused by mixing using angular.js, your thoughts?

**Comment by milankinen** [comment]
@ilovepumpkin Yeah it depends what you are trying to reload. Naturally only React components get reloaded. If you are mixing Angular and React stuff in your module, then you might have issues.

Isn't it working even if you modify some module that exports **only** one react component?

**Comment by ilovepumpkin** [comment]
@milankinen , my doubt is that the react component is truly reloaded but angular does not reload the reloaded react components. But as I know our project is moving the pure React implementation soon, so your library should work by that time.

**Comment by mikeebee** [comment]
@milankinen: Installed `2.3.0-rc7` and now the circular dependancy is gone.

Now I see this, console claims all is well but no changes seen.

livereactload

<details>
<summary>Also, I tried adding the `debug` option to my Gulp file but I get this error.</summary>
```
Error: Cannot find module '[object Object]' from '[PROJECT_FOLDER]]'
    at Function.module.exports [as sync] ([PROJECT_FOLDER]]/node_modules/browserify/node_modules/resolve/lib/sync.js:33:11)
    at Browserify.plugin ([PROJECT_FOLDER]]/node_modules/browserify/index.js:354:29)
    at [PROJECT_FOLDER]]/node_modules/browserify/index.js:97:14
    at Array.forEach (native)
    at new Browserify ([PROJECT_FOLDER]]/node_modules/browserify/index.js:96:44)
    at Browserify ([PROJECT_FOLDER]]/node_modules/browserify/index.js:38:47)
    at browserifyTask ([PROJECT_FOLDER]]/gulpfile.js:87:22)
    at Gulp.<anonymous> ([PROJECT_FOLDER]]/gulpfile.js:181:5)
    at module.exports ([PROJECT_FOLDER]]/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask ([PROJECT_FOLDER]]/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep ([PROJECT_FOLDER]]/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at [PROJECT_FOLDER]]/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish ([PROJECT_FOLDER]]/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports ([PROJECT_FOLDER]]/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask ([PROJECT_FOLDER]]/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep ([PROJECT_FOLDER]]/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start ([PROJECT_FOLDER]]/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
```
</details>
<details>
<summary>This is my Gulp Task</summary>
```
var browserifyTask = function(options) {
    // Our app bundler
    var appBundler = browserify({
        entries: [options.src], // Only need initial file, browserify finds the rest
        transform: [
            // Some settings are in /.babelrc
            ['babelify'],
            ['envify', {
                'global': true,
                '_': 'purge',
                NODE_ENV: 'production'}
            ]
        ], // We want to convert JSX to normal javascript
        plugin:  !options.development ? [] : [ lrload, { 'debug': true } ],    // no additional configuration is needed
        debug: options.development, // Gives us sourcemapping
        cache: {},
        packageCache: {},
        fullPaths: options.development // Requirement of watchify
    });
    // The rebundle process
    var rebundle = function() {
        var start = Date.now();
        console.log('Building APP bundle');
        appBundler
            .bundle()
            .on('error', errorHandler)
            .pipe(source(inputOutput.jsOutput))
            .pipe(gulpif(!options.development, streamify(uglify())))
            .pipe(gulp.dest(options.dest))
            .pipe(gulpif(options.development, livereload()))
            .pipe(notify(function() {
                console.log('APP bundle built in ' + (Date.now() - start) + 'ms');
            }));
    };

    // Fire up Watchify when developing
    if (options.development) {
        appBundler = watchify(appBundler);
        appBundler.on('update', rebundle);
    }

    rebundle();
};
```
</details>

**Comment by milankinen** [comment]
@mikeebee Strange... What kind of change did you make to your codebase? There are some cases when the changes are not applied (mostly because of closures and their scopes) but I cannot tell more unless you provide more details. Did you modify an existing React component or some kind of "utility" function? Did you modify the root/entry module or some child module/component?

Thanks!

About your gulp error. You forgot to add array bracket around the plugin definition:
```diff
        ], // We want to convert JSX to normal javascript
-       plugin: !options.development ? [] : [ lrload, { 'debug': true } ],    
+       plugin: !options.development ? [] : [ [lrload, { 'debug': true }] ],
        debug
```

**Comment by milankinen** [comment]
Okay I'll merge this to `development` and wait few more days. If nothing new happens, I'll then merge this to `master` and make an official release.

Just noticed that I've removed `--client` option which makes this a major release ('cause semver), thus the new release will be `3.0.0`

**Comment by mikeebee** [comment]
@milankinen finally figured it out! You've been hinting at this being a possible issue along the way but my lack of understanding made me blind to it :/

In this project, ALL components are extended from a set of 'core' components, I believe to add some additional core features. For example, this one is for general components (and the most basic example)...

<details>
<summary>'Node' component</summary>
```javascript
import React, { Component } from 'react';

export default class Node extends Component {
	// Conditional classes
	getClassName() {
		return;
	}

	// You will only set render on subclasses
	render() {
		return;
	}
}
```
</details>

<details>
<summary>... which is used like this</summary>
```javascript
import React, { PropTypes } from 'react';
import * as Core from './core/';

class NewComponent extends Core.Node {

	render() {
		return (
			<div>Some stuff here</div>
		)
	}
}
```
</details>

If I alter the core component, the changes appear as expected!

The above example is the simplest form, other 'core' components are more complex. Meaning I can't simply remove their usage to get this working across the board.

Is there a workaround for this? *crosses fingers*

**Comment by milankinen** [comment]
@mikeebee Thanks! Those are very helpful discoverings. I think the problem lies in `react-transform` which doesn't recognize your `Core.Node` as a valid superclass, please see [this](https://github.com/gaearon/babel-plugin-react-transform/blob/master/src/index.js#L174).

Luckily the plugin seems to have a support for custom super classes. So if you modified your `.babelrc` config file, the reloading would (hopefully) start to work:

```json
{
  "presets": ["es2015", "react"],
  "env": {
    "development": {
      "plugins": [
        ["react-transform", {
          "superClasses": ["React.Component", "Component", "Core.Node", "Node"],
          "transforms": [{
            "transform": "livereactload/babel-transform",
            "imports": ["react"]
          }]
        }]
      ]
    }
  }
}
```

**Comment by mikeebee** [comment]
@milankinen yes that worked a charm! Looks like I'm all sorted then. 

Thank you so much for taking the time to work through this with me. You're a gem.

**Comment by mikeebee** [comment]
I'm not sure if this will be related to the re-write but I'm getting an error in iOS (8.4).

```javascript
 TypeError: undefined is not a function (evaluating 'Object.assign(scope, {
    compile: compile,
    load: load
  })')
```

Do I somehow need to run this through Babelify?

**Comment by milankinen** [comment]
Thanks! 😄  It seems that iOS 8.4 doesn't support `Object.assign`. I'll fix that later today.

**Comment by mikeebee** [comment]
@milankinen also getting this error on IE11

**Comment by mikeebee** [comment]
@milankinen hey! Any idea when you might be able to make this fix?

**Comment by milankinen** [comment]
@mikeebee Thanks for kicking in some action. I released the official version `3.0.0` containing the improvements from this branch.

**Comment by mikeebee** [comment]
@milankinen Perfect, thanks so much for your effort on this!

**Pull request merged**
